import React from 'react';
import { CrudTemplate } from '../components/crud-template';

// Sample data for reports
const reportsData = [
  {
    id: '1',
    reportName: 'Monthly Patient Statistics',
    category: 'Administrative',
    generatedBy: 'Dr. John Smith',
    generatedOn: '2025-03-31',
    period: 'March 2025',
    status: 'Completed',
    fileSize: '2.4 MB',
    format: 'PDF',
    description: 'Monthly statistics of patient admissions, discharges, and treatments.'
  },
  {
    id: '2',
    reportName: 'Quarterly Medication Usage',
    category: 'Pharmacy',
    generatedBy: 'Sarah Johnson',
    generatedOn: '2025-04-01',
    period: 'Q1 2025',
    status: 'Completed',
    fileSize: '3.7 MB',
    format: 'Excel',
    description: 'Analysis of medication consumption and costs for Q1 2025.'
  },
  {
    id: '3',
    reportName: 'Annual Equipment Audit',
    category: 'Inventory',
    generatedBy: 'Michael Chen',
    generatedOn: '2025-01-15',
    period: '2024',
    status: 'Archived',
    fileSize: '5.1 MB',
    format: 'PDF',
    description: 'Complete audit of all hospital equipment including condition assessment.'
  },
  {
    id: '4',
    reportName: 'Weekly Staff Schedule',
    category: 'Human Resources',
    generatedBy: 'Emily Rodriguez',
    generatedOn: '2025-04-21',
    period: 'Apr 21-27, 2025',
    status: 'Current',
    fileSize: '1.2 MB',
    format: 'PDF',
    description: 'Staff rotation schedule for all departments for the current week.'
  }
];

// Table columns configuration
const columns = [
  {
    key: 'reportName',
    label: 'REPORT NAME',
    render: (item) => (
      <div>
        <div className="font-medium">{item.reportName}</div>
        <div className="text-default-500 text-xs">{item.category}</div>
      </div>
    )
  },
  {
    key: 'generatedInfo',
    label: 'GENERATED',
    render: (item) => (
      <div>
        <div className="font-medium">{item.generatedOn}</div>
        <div className="text-default-500 text-xs">By: {item.generatedBy}</div>
      </div>
    )
  },
  { key: 'period', label: 'PERIOD' },
  {
    key: 'fileInfo',
    label: 'FILE',
    render: (item) => (
      <div>
        <div className="font-medium">{item.format}</div>
        <div className="text-default-500 text-xs">{item.fileSize}</div>
      </div>
    )
  },
  { key: 'status', label: 'STATUS' },
  { key: 'actions', label: 'ACTIONS' }
];

// Form fields for add/edit dialog
const formFields = [
  { key: 'reportName', label: 'Report Name', type: 'text', required: true },
  { key: 'category', label: 'Category', type: 'select', required: true, options: [
    { value: 'Administrative', label: 'Administrative' },
    { value: 'Pharmacy', label: 'Pharmacy' },
    { value: 'Inventory', label: 'Inventory' },
    { value: 'Human Resources', label: 'Human Resources' },
    { value: 'Financial', label: 'Financial' },
    { value: 'Clinical', label: 'Clinical' }
  ]},
  { key: 'generatedBy', label: 'Generated By', type: 'text', required: true },
  { key: 'generatedOn', label: 'Generated On', type: 'date', required: true },
  { key: 'period', label: 'Period', type: 'text', required: true },
  { key: 'format', label: 'File Format', type: 'select', options: [
    { value: 'PDF', label: 'PDF' },
    { value: 'Excel', label: 'Excel' },
    { value: 'Word', label: 'Word' },
    { value: 'CSV', label: 'CSV' }
  ]},
  { key: 'fileSize', label: 'File Size', type: 'text' },
  { key: 'description', label: 'Description', type: 'textarea' },
  { key: 'status', label: 'Status', type: 'select', options: [
    { value: 'Current', label: 'Current' },
    { value: 'Completed', label: 'Completed' },
    { value: 'Archived', label: 'Archived' },
    { value: 'Draft', label: 'Draft' }
  ]}
];

// Initial form data for new reports
const initialFormData = {
  reportName: '',
  category: '',
  generatedBy: '',
  generatedOn: '',
  period: '',
  status: 'Draft',
  fileSize: '',
  format: 'PDF',
  description: ''
};

function ReportsPage() {
  return (
    <CrudTemplate
      title="Reports"
      description="Access and manage hospital reports"
      icon="lucide:file-text"
      columns={columns}
      data={reportsData}
      initialFormData={initialFormData}
      formFields={formFields}
      addButtonLabel="Generate Report"
    />
  );
}

export default ReportsPage;