[
    {
        "id": 15,
        "patient_id": 10,
        "doctor_id": 44,
        "issued_by": 20,
        "invoice_number": "INV-20250611-094055-2",
        "invoice_date": "2025-06-13",
        "total_amount": "500.00",
        "discount_amount": "50.00",
        "net_amount": "450.00",
        "paid": 10,
        "payment_method": null,
        "notes": null,
        "created_at": "2025-06-11 09:40:56",
        "updated_at": "2025-06-11 09:40:56",
        "created_by": null,
        "updated_by": null,
        "patient": {
            "id": 10,
            "user_id": 40,
            "full_name": "Patient 1",
            "father_name": "Patient 1 ka Baap",
            "email": "patient1@gmail.com",
            "contact_number": "030000000000",
            "gender": "male",
            "age": 40,
            "address": "Patient Address",
            "medical_history": "No",
            "allergies": "Yes",
            "created_at": "2025-04-28 13:03:28",
            "updated_at": "2025-04-28 14:09:02",
            "created_by": 31,
            "updated_by": 31
        },
        "doctor": {
            "id": 44,
            "role": "doctor",
            "username": "Doctor3",
            "email": "doctor3@gmail.com",
            "password_hash": "$2y$13$kLSk3kauWmimybMNehxGAuwbsyGf8Cvcbntd/IIwAM28DR/tbAOTG",
            "verified": 1,
            "auth_key": null,
            "access_token": null,
            "token_expire_at": null,
            "refresh_token": null,
            "active": 1,
            "created_at": "2025-05-07 14:45:11",
            "updated_at": "2025-05-07 16:42:28",
            "created_by": null,
            "updated_by": null
        },
        "items": [
            {
                "id": 16,
                "invoice_id": 15,
                "item_type": "",
                "item_description": "Root canal treatment",
                "quantity": 50,
                "unit_price": "10.00",
                "discount": "0.00",
                "total_price": "500.00",
                "created_at": "2025-06-11 09:40:56",
                "updated_at": "2025-06-11 09:40:56",
                "created_by": null,
                "updated_by": null
            }
        ],
        "due_amount": 440,
        "after_discount": 450,
        "active": "No",
        "is_expired": "No"
    },
    {
        "id": 14,
        "patient_id": 10,
        "doctor_id": 44,
        "issued_by": 20,
        "invoice_number": "INV-20250611-093512-291",
        "invoice_date": "2025-06-13",
        "total_amount": "1000.00",
        "discount_amount": "100.00",
        "net_amount": "900.00",
        "paid": 100,
        "payment_method": null,
        "notes": null,
        "created_at": "2025-06-11 09:35:12",
        "updated_at": "2025-06-11 09:35:12",
        "created_by": null,
        "updated_by": null,
        "patient": {
            "id": 10,
            "user_id": 40,
            "full_name": "Patient 1",
            "father_name": "Patient 1 ka Baap",
            "email": "patient1@gmail.com",
            "contact_number": "030000000000",
            "gender": "male",
            "age": 40,
            "address": "Patient Address",
            "medical_history": "No",
            "allergies": "Yes",
            "created_at": "2025-04-28 13:03:28",
            "updated_at": "2025-04-28 14:09:02",
            "created_by": 31,
            "updated_by": 31
        },
        "doctor": {
            "id": 44,
            "role": "doctor",
            "username": "Doctor3",
            "email": "doctor3@gmail.com",
            "password_hash": "$2y$13$kLSk3kauWmimybMNehxGAuwbsyGf8Cvcbntd/IIwAM28DR/tbAOTG",
            "verified": 1,
            "auth_key": null,
            "access_token": null,
            "token_expire_at": null,
            "refresh_token": null,
            "active": 1,
            "created_at": "2025-05-07 14:45:11",
            "updated_at": "2025-05-07 16:42:28",
            "created_by": null,
            "updated_by": null
        },
        "items": [
            {
                "id": 15,
                "invoice_id": 14,
                "item_type": "",
                "item_description": "Root canal treatment",
                "quantity": 10,
                "unit_price": "100.00",
                "discount": "0.00",
                "total_price": "1000.00",
                "created_at": "2025-06-11 09:35:12",
                "updated_at": "2025-06-11 09:35:12",
                "created_by": null,
                "updated_by": null
            }
        ],
        "due_amount": 800,
        "after_discount": 900,
        "active": "No",
        "is_expired": "No"
    },
    {
        "id": 13,
        "patient_id": 10,
        "doctor_id": 44,
        "issued_by": 20,
        "invoice_number": "INV-20250611-092440-609",
        "invoice_date": "2025-06-13",
        "total_amount": "1700.00",
        "discount_amount": "170.00",
        "net_amount": "1530.00",
        "paid": 127,
        "payment_method": null,
        "notes": null,
        "created_at": "2025-06-11 09:24:40",
        "updated_at": "2025-06-11 09:24:40",
        "created_by": null,
        "updated_by": null,
        "patient": {
            "id": 10,
            "user_id": 40,
            "full_name": "Patient 1",
            "father_name": "Patient 1 ka Baap",
            "email": "patient1@gmail.com",
            "contact_number": "030000000000",
            "gender": "male",
            "age": 40,
            "address": "Patient Address",
            "medical_history": "No",
            "allergies": "Yes",
            "created_at": "2025-04-28 13:03:28",
            "updated_at": "2025-04-28 14:09:02",
            "created_by": 31,
            "updated_by": 31
        },
        "doctor": {
            "id": 44,
            "role": "doctor",
            "username": "Doctor3",
            "email": "doctor3@gmail.com",
            "password_hash": "$2y$13$kLSk3kauWmimybMNehxGAuwbsyGf8Cvcbntd/IIwAM28DR/tbAOTG",
            "verified": 1,
            "auth_key": null,
            "access_token": null,
            "token_expire_at": null,
            "refresh_token": null,
            "active": 1,
            "created_at": "2025-05-07 14:45:11",
            "updated_at": "2025-05-07 16:42:28",
            "created_by": null,
            "updated_by": null
        },
        "items": [
            {
                "id": 14,
                "invoice_id": 13,
                "item_type": "",
                "item_description": "Root canal treatment",
                "quantity": 10,
                "unit_price": "170.00",
                "discount": "0.00",
                "total_price": "1700.00",
                "created_at": "2025-06-11 09:24:40",
                "updated_at": "2025-06-11 09:24:40",
                "created_by": null,
                "updated_by": null
            }
        ],
        "due_amount": 1403,
        "after_discount": 1530,
        "active": "No",
        "is_expired": "No"
    },
    {
        "id": 12,
        "patient_id": 10,
        "doctor_id": 43,
        "issued_by": 20,
        "invoice_number": "INV-20250611-091833-757",
        "invoice_date": "2025-06-12",
        "total_amount": "7000.00",
        "discount_amount": "2800.00",
        "net_amount": "4200.00",
        "paid": 127,
        "payment_method": null,
        "notes": null,
        "created_at": "2025-06-11 09:18:33",
        "updated_at": "2025-06-11 09:18:33",
        "created_by": null,
        "updated_by": null,
        "patient": {
            "id": 10,
            "user_id": 40,
            "full_name": "Patient 1",
            "father_name": "Patient 1 ka Baap",
            "email": "patient1@gmail.com",
            "contact_number": "030000000000",
            "gender": "male",
            "age": 40,
            "address": "Patient Address",
            "medical_history": "No",
            "allergies": "Yes",
            "created_at": "2025-04-28 13:03:28",
            "updated_at": "2025-04-28 14:09:02",
            "created_by": 31,
            "updated_by": 31
        },
        "doctor": {
            "id": 43,
            "role": "doctor",
            "username": "Doctor2",
            "email": "doctor2@gmail.com",
            "password_hash": "$2y$13$nWMIe.ncag8EXPto5XfZruTrYd6SBf05Xk1B.X7ecsKWDlS.3l9mO",
            "verified": 0,
            "auth_key": null,
            "access_token": null,
            "token_expire_at": null,
            "refresh_token": null,
            "active": 1,
            "created_at": "2025-05-07 14:33:29",
            "updated_at": "2025-05-07 14:34:16",
            "created_by": null,
            "updated_by": null
        },
        "items": [
            {
                "id": 13,
                "invoice_id": 12,
                "item_type": "",
                "item_description": "Dental X-ray imaging",
                "quantity": 10,
                "unit_price": "700.00",
                "discount": "0.00",
                "total_price": "7000.00",
                "created_at": "2025-06-11 09:18:34",
                "updated_at": "2025-06-11 09:18:34",
                "created_by": null,
                "updated_by": null
            }
        ],
        "due_amount": 4073,
        "after_discount": 4200,
        "active": "No",
        "is_expired": "No"
    }
]